config/routes.rb
Rails.application.routes.draw do


  root to: 'static_pages#home'
  get "home", to: 'static_pages#home'
  get "help", to: 'static_pages#help'
  get "about", to: 'static_pages#about'
  get "contact", to: 'static_pages#contact'
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login" ,to: 'sessions#new'
  post "login" ,to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users
  resources :microposts, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true ,length:{ maximum: 140}
  validate :picture_size

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture,  "容量が大き過ぎます")
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length:{maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length:{maximum:255},
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: {case_sensitive:false }

  has_secure_password
  validates :password, presence: true, length:{minimum:6},allow_nil: true
  has_many :microposts, dependent: :destroy

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  #永続セッションの為にユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest,User.digest(remember_token))
  end

  #渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest,nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  def logged_in_user
    unless logged_in?
      store_location
      redirect_to login_path, alert:"ログインしてください"
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      redirect_to root_path, notice:"投稿しました"
    else
      render "static_pages/home"
    end
  end

  def destroy
    @micropost.destroy
    redirect_to request.referrer || root_path ,notice:"削除しました"
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id:params[:id])
      redirect_to root_path if @micropost.nil?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        log_in user
        params[:session][:remember_me] == "1" ? remember(user):forget(user)
        redirect_back_or user 
      else
        flash.now[:alert] = 'emailかpasswordが間違えています'
        render :new 
      end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_path
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build if logged_in?
  end

  def help
  end

  def about
  end
  
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy


  def index
    @users = User.page(params[:page]).order(created_at: :asc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user, notice:"ようこそ！"
    else 
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, notice:"更新しました"
    else
      render :edit ,alert:"更新できませんでした"
    end
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to users_path, notice:"削除しました"
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + '|' + base_title
    end

  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  #ユーザーのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end


  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: session[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @cuurent_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
#記憶したURL(もしくはデフォルト値)にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url]|| default)
    session.delete(:forwarding_url)
  end
#アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwading_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのgravatar画像を返す
  def gravatar_for(user, size:80)
    gravatar_id =  Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url =  "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class:"gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
        The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "about", about_path %></li>
      <li><%= link_to "contact",contact_path%></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
  </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user)%></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if notice%>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>
    <% if alert%>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
    <% end %>
  <div class="container">
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size:50),micropost.user %>
  <span class="user"><%= link_to micropost.user.name %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture?%>
  </span>
  <span class="timestamp">
    投稿 <%= time_ago_in_words(micropost.created_at) %>前.
  <% if current_user?(current_user)%>
    <%= link_to "削除", micropost, method: :delete, data: { confirm: "削除しますか？"}%></span>
  <% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object%>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
    <%= f.submit "投稿する", class:"btn btn-warning"%>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'  %>
    </span>
  <% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size:50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィール", current_user%></span>
<span><%= pluralize(current_user.microposts.count, "投稿") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>tweet app</h1>

  <h2>
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <p>これからtweet appを作っていくよ！</p>

  <%= link_to "sign up now!", signup_path, class:"btn btn-lg btn-success" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
<% end %>

app/views/users/_form.html.erb
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages" ,object: f.object%>
      <%= f.label :name %>
      <%= f.text_field :name ,placeholder: "name", class:"form-control"%>

      <%= f.label :email %>
      <%= f.email_field :email, placeholder: "email", class:"form-control"%>

      <%= f.label :password %>
      <%= f.password_field :password , placeholder: "password", class:"form-control"%>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation , placeholder: "password" , class:"form-control"%>

      <%= f.submit yield(:button_text), class:"btn btn-warning" %>
    <% end %>

app/views/users/_user.html.erb
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user ,size:50%>
      <%= link_to user.name, user%>
      <% if current_user.admin? && !current_user?(user)%>
      | <%= link_to "delete", user, method: :delete,  data: {confirm: "本当に消しますか？"}%>
      <% end %>
    </li>
  <% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー設定")%>
<% provide(:button_text, "更新する")%>
<h1>プロフィール編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form"%>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">変更する</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧")%>
<h1>ユーザー一覧</h1>

  <%= page_entries_info @users %>
  <br>
  <%= paginate @users %>
<ul class="users">
  <%= render @users%>
</ul>
<%= paginate @users %>

app/views/users/new.html.erb
<% provide(:title , "sign up") %>
<% provide(:button_text, "アカウント作成")%>
<h1>sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset3">
    <%= render "form"%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name ) %>
<div class="row">
  <aside class="col-md-4">
    <secsion class="user-info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </secsion>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>投稿(<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= paginate @microposts %>
    <% end %>
  </div>
</div>